/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as BBrandIdRouteImport } from './routes/b.$brandId'
import { Route as BBrandIdListRouteImport } from './routes/b.$brandId.list'
import { Route as BBrandIdIdeasRouteImport } from './routes/b.$brandId.ideas'
import { Route as BBrandIdCalendarRouteImport } from './routes/b.$brandId.calendar'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BBrandIdRoute = BBrandIdRouteImport.update({
  id: '/b/$brandId',
  path: '/b/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const BBrandIdListRoute = BBrandIdListRouteImport.update({
  id: '/list',
  path: '/list',
  getParentRoute: () => BBrandIdRoute,
} as any)
const BBrandIdIdeasRoute = BBrandIdIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => BBrandIdRoute,
} as any)
const BBrandIdCalendarRoute = BBrandIdCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => BBrandIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/b/$brandId': typeof BBrandIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/b/$brandId/calendar': typeof BBrandIdCalendarRoute
  '/b/$brandId/ideas': typeof BBrandIdIdeasRoute
  '/b/$brandId/list': typeof BBrandIdListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/b/$brandId': typeof BBrandIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/b/$brandId/calendar': typeof BBrandIdCalendarRoute
  '/b/$brandId/ideas': typeof BBrandIdIdeasRoute
  '/b/$brandId/list': typeof BBrandIdListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/b/$brandId': typeof BBrandIdRouteWithChildren
  '/share/$token': typeof ShareTokenRoute
  '/b/$brandId/calendar': typeof BBrandIdCalendarRoute
  '/b/$brandId/ideas': typeof BBrandIdIdeasRoute
  '/b/$brandId/list': typeof BBrandIdListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brands'
    | '/login'
    | '/settings'
    | '/b/$brandId'
    | '/share/$token'
    | '/b/$brandId/calendar'
    | '/b/$brandId/ideas'
    | '/b/$brandId/list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brands'
    | '/login'
    | '/settings'
    | '/b/$brandId'
    | '/share/$token'
    | '/b/$brandId/calendar'
    | '/b/$brandId/ideas'
    | '/b/$brandId/list'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/brands'
    | '/login'
    | '/settings'
    | '/b/$brandId'
    | '/share/$token'
    | '/b/$brandId/calendar'
    | '/b/$brandId/ideas'
    | '/b/$brandId/list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  BBrandIdRoute: typeof BBrandIdRouteWithChildren
  ShareTokenRoute: typeof ShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$brandId': {
      id: '/b/$brandId'
      path: '/b/$brandId'
      fullPath: '/b/$brandId'
      preLoaderRoute: typeof BBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b/$brandId/list': {
      id: '/b/$brandId/list'
      path: '/list'
      fullPath: '/b/$brandId/list'
      preLoaderRoute: typeof BBrandIdListRouteImport
      parentRoute: typeof BBrandIdRoute
    }
    '/b/$brandId/ideas': {
      id: '/b/$brandId/ideas'
      path: '/ideas'
      fullPath: '/b/$brandId/ideas'
      preLoaderRoute: typeof BBrandIdIdeasRouteImport
      parentRoute: typeof BBrandIdRoute
    }
    '/b/$brandId/calendar': {
      id: '/b/$brandId/calendar'
      path: '/calendar'
      fullPath: '/b/$brandId/calendar'
      preLoaderRoute: typeof BBrandIdCalendarRouteImport
      parentRoute: typeof BBrandIdRoute
    }
  }
}

interface BBrandIdRouteChildren {
  BBrandIdCalendarRoute: typeof BBrandIdCalendarRoute
  BBrandIdIdeasRoute: typeof BBrandIdIdeasRoute
  BBrandIdListRoute: typeof BBrandIdListRoute
}

const BBrandIdRouteChildren: BBrandIdRouteChildren = {
  BBrandIdCalendarRoute: BBrandIdCalendarRoute,
  BBrandIdIdeasRoute: BBrandIdIdeasRoute,
  BBrandIdListRoute: BBrandIdListRoute,
}

const BBrandIdRouteWithChildren = BBrandIdRoute._addFileChildren(
  BBrandIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  BBrandIdRoute: BBrandIdRouteWithChildren,
  ShareTokenRoute: ShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
